version: '3.8'

services:
  file-service:
    image: file-service
    container_name: file-service
    build: .
    ports:
      - 8080:8080
    networks:
      - device-backend
    environment:
      DB_HOST: file-service-db
      DB_PORT: 5432
      DB_USERNAME: app
      DB_PASSWORD: pass
    depends_on:
      - file-service-db

  file-service-db:
    image: library/postgres:11
    container_name: file-service-db
    expose:
      - "5432"
    networks:
      - device-backend
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: app
      POSTGRES_PASSWORD: pass
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro

networks:
  device-backend:
    external:
      name: device-backend