spring:
  application:
    name: file-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME:app}
    password: ${DB_PASSWORD:pass}

fileservice:
  root:
    path: /Users/amir/work/projects/education_it_park
