spring:
  application:
    name: file-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:8432}/db
    username: ${DB_USERNAME:app}
    password: ${DB_PASSWORD:pass}

fileservice:
  root:
    path: ${FILE_PATH:/Users/amir/work/projects/education_it_park}

security:
  oauth2:
    client:
      client-id: devicerenter
      client-secret: devicerentersecret
    resource:
      jwt:
        key-uri: http://localhost:7777/oauth/token_key