spring:
  application:
    name: file-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/db
    username: ${DB_USERNAME:app}
    password: ${DB_PASSWORD:pass}

fileservice:
  root:
    path: /Users/amir/work/projects/education_it_park
